from tkinter import Tk, W, E
from tkinter.ttk import Frame, Button, Entry, Style

class Calender(Frame):

    def __init__(self,window):
        super().__init__()
        self.window = window

        self.initUI()

    def initUI(self):

        self.window.title("Calendar")

        Style().configure("TButton", padding=(15, 14, 12, 15),
            font='serif 10')

        self.columnconfigure(0, pad=3)
        self.columnconfigure(1, pad=3)
        self.columnconfigure(2, pad=3)
        self.columnconfigure(3, pad=3)
        self.columnconfigure(4, pad=3)
        self.columnconfigure(5, pad=3)
        self.columnconfigure(6, pad=3)
        

        self.rowconfigure(0, pad=3)
        self.rowconfigure(1, pad=3)
        self.rowconfigure(2, pad=3)
        self.rowconfigure(3, pad=3)
        self.rowconfigure(4, pad=3)
        self.rowconfigure(5, pad=3)
        self.rowconfigure(6, pad=3)
        self.rowconfigure(7, pad=3)
        self.rowconfigure(8, pad=3)
        self.rowconfigure(9, pad=3)
        self.rowconfigure(10, pad=3)


        sun1 = Button(self.window, text="Sun 9 a.m.")
        sun1.grid(row=1, column=0)
        mon1 = Button(self.window, text="Mon 9 a.m.")
        mon1.grid(row=1, column=1)
        tue1 = Button(self.window,text = 'Tue 9 a.m.')
        tue1.grid(row=1, column=2)
        wed1 = Button(self.window, text="Wed 9 a.m.")
        wed1.grid(row=1, column=3)
        thu1 = Button(self.window, text="Thu 9 a.m.")
        thu1.grid(row=1, column=4)
        fri1 = Button(self.window, text="Fri 9 a.m.")
        fri1.grid(row=1, column=5)
        sat1 = Button(self.window, text="Sat 9 a.m.")
        sat1.grid(row=1, column=6)
        
        sun2 = Button(self.window, text="Sun 10 a.m.")
        sun2.grid(row=2, column=0)
        mon2 = Button(self.window, text="Mon 10 a.m.")
        mon2.grid(row=2, column=1)
        tue2 = Button(self.window,text = 'Tue 10 a.m.')
        tue2.grid(row=2, column=2)
        wed2 = Button(self.window, text="Wed 10 a.m.")
        wed2.grid(row=2, column=3)
        thu2 = Button(self.window, text="Thu 10 a.m.")
        thu2.grid(row=2, column=4)
        fri2 = Button(self.window, text="Fri 10 a.m.")
        fri2.grid(row=2, column=5)
        sat2 = Button(self.window, text="Sat 10 a.m.")
        sat2.grid(row=2, column=6)

        sun3 = Button(self.window, text="Sun 11 a.m.")
        sun3.grid(row=3, column=0)
        mon3 = Button(self.window, text="Mon 11 a.m.")
        mon3.grid(row=3, column=1)
        tue3 = Button(self.window,text = 'Tue 11 a.m.')
        tue3.grid(row=3, column=2)
        wed3 = Button(self.window, text="Wed 11 a.m.")
        wed3.grid(row=3, column=3)
        thu3 = Button(self.window, text="Thu 11 a.m.")
        thu3.grid(row=3, column=4)
        fri3 = Button(self.window, text="Fri 11 a.m.")
        fri3.grid(row=3, column=5)
        sat3 = Button(self.window, text="Sat 11 a.m.")
        sat3.grid(row=3, column=6)

        sun4 = Button(self.window, text="Sun 12 a.m.")
        sun4.grid(row=4, column=0)
        mon4 = Button(self.window, text="Mon 12 a.m.")
        mon4.grid(row=4, column=1)
        tue4 = Button(self.window,text = 'Tue 12 a.m.')
        tue4.grid(row=4, column=2)
        wed4 = Button(self.window, text="Wed 12 a.m.")
        wed4.grid(row=4, column=3)
        thu4 = Button(self.window, text="Thu 12 a.m.")
        thu4.grid(row=4, column=4)
        fri4 = Button(self.window, text="Fri 12 a.m.")
        fri4.grid(row=4, column=5)
        sat4 = Button(self.window, text="Sat 12 a.m.")
        sat4.grid(row=4, column=6)

        sun5 = Button(self.window, text="Sun 1 p.m.")
        sun5.grid(row=5, column=0)
        mon5 = Button(self.window, text="Mon 1 p.m.")
        mon5.grid(row=5, column=1)
        tue5 = Button(self.window,text = 'Tue 1 p.m.')
        tue5.grid(row=5, column=2)
        wed5 = Button(self.window, text="Wed 1 p.m.")
        wed5.grid(row=5, column=3)
        thu5 = Button(self.window, text="Thu 1 p.m.")
        thu5.grid(row=5, column=4)
        fri5 = Button(self.window, text="Fri 1 p.m.")
        fri5.grid(row=5, column=5)
        sat5 = Button(self.window, text="Sat 1 p.m.")
        sat5.grid(row=5, column=6)

        sun6 = Button(self.window, text="Sun 2 p.m.")
        sun6.grid(row=6, column=0)
        mon6 = Button(self.window, text="Mon 2 p.m.")
        mon6.grid(row=6, column=1)
        tue6 = Button(self.window,text = 'Tue 2 p.m.')
        tue6.grid(row=6, column=2)
        wed6 = Button(self.window, text="Wed 2 p.m.")
        wed6.grid(row=6, column=3)
        thu6 = Button(self.window, text="Thu 2 p.m.")
        thu6.grid(row=6, column=4)
        fri6 = Button(self.window, text="Fri 2 p.m.")
        fri6.grid(row=6, column=5)
        sat6 = Button(self.window, text="Sat 2 p.m.")
        sat6.grid(row=6, column=6)

        sun7 = Button(self.window, text="Sun 3 p.m.")
        sun7.grid(row=7, column=0)
        mon7 = Button(self.window, text="Mon 3 p.m.")
        mon7.grid(row=7, column=1)
        tue7 = Button(self.window,text ='Tue 3 p.m.')
        tue7.grid(row=7, column=2)
        wed7 = Button(self.window, text="Wed 3 p.m.")
        wed7.grid(row=7, column=3)
        thu7 = Button(self.window, text="Thu 3 p.m.")
        thu7.grid(row=7, column=4)
        fri7 = Button(self.window, text="Fri 3 p.m.")
        fri7.grid(row=7, column=5)
        sat7 = Button(self.window, text="Sat 3 p.m.")
        sat7.grid(row=7, column=6)

        sun8 = Button(self.window, text="Sun 4 p.m.")
        sun8.grid(row=8, column=0)
        mon8 = Button(self.window, text="Mon 4 p.m.")
        mon8.grid(row=8, column=1)
        tue8 = Button(self.window,text ='Tue 4 p.m.')
        tue8.grid(row=8, column=2)
        wed8 = Button(self.window, text="Wed 4 p.m.")
        wed8.grid(row=8, column=3)
        thu8 = Button(self.window, text="Thu 4 p.m.")
        thu8.grid(row=8, column=4)
        fri8 = Button(self.window, text="Fri 4 p.m.")
        fri8.grid(row=8, column=5)
        sat8 = Button(self.window, text="Sat 4 p.m.")
        sat8.grid(row=8, column=6)

        sun9 = Button(self.window, text="Sun 5 p.m.")
        sun9.grid(row=9, column=0)
        mon9 = Button(self.window, text="Mon 5 p.m.")
        mon9.grid(row=9, column=1)
        tue9 = Button(self.window,text ='Tue 5 p.m.')
        tue9.grid(row=9, column=2)
        wed9 = Button(self.window, text="Wed 5 p.m.")
        wed9.grid(row=9, column=3)
        thu9 = Button(self.window, text="Thu 5 p.m.")
        thu9.grid(row=9, column=4)
        fri9 = Button(self.window, text="Fri 5 p.m.")
        fri9.grid(row=9, column=5)
        sat9 = Button(self.window, text="Sat 5 p.m.")
        sat9.grid(row=9, column=6)

        sun10 = Button(self.window, text="Sun 6 p.m.")
        sun10.grid(row=10, column=0)
        mon10 = Button(self.window, text="Mon 6 p.m.")
        mon10.grid(row=10, column=1)
        tue10 = Button(self.window,text ='Tue 6 p.m.')
        tue10.grid(row=10, column=2)
        wed10 = Button(self.window, text="Wed 6 p.m.")
        wed10.grid(row=10, column=3)
        thu10 = Button(self.window, text="Thu 6 p.m.")
        thu10.grid(row=10, column=4)
        fri10 = Button(self.window, text="Fri 6 p.m.")
        fri10.grid(row=10, column=5)
        sat10 = Button(self.window, text="Sat 6 p.m.")
        sat10.grid(row=10, column=6)


        self.pack()





#window = Tk()
#window.geometry("853x480")
#table = Calender()
#window.mainloop()


